### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by eduardozgz**

### CODE REVIEW

**Comment by phoebe-leong** [comment]
You own the repo right? Can't you just push these changes to the project instead of opening a PR?

**Comment by eduardozgz** [comment]
This is manged automatically by crowdin, but I could try

**Comment by phoebe-leong** [comment]
Oh right ok. Thank you for explaining it to me!

**Comment by eduardozgz** [comment]
@phoebe-leong I found some reasons to stay with the pull requests

1. I can verify the translations before includig them in the dev branch, so I could avoid spam going live in the Beta bot

2. I would reduce any CI overload since this is commited every 10 minutes if there are any changes in the translation proyect

3. I can squash all the commits and then merge it easily

**Pull request merged**
